## Cari nilai x,y,z dengan Gauss - Jordan

In [21]:
import numpy as np
import re
from sympy import symbols, Eq, sympify

def parse_equations(equations):
    variables = set(re.findall(r'[a-zA-Z]', ' '.join(equations)))
    variables = sorted(variables)
    symbols_dict = {var: symbols(var) for var in variables}
    symbol_list = [symbols_dict[var] for var in variables]
    coefficients = []
    constants = []

    for eq in equations:
        lhs, rhs = eq.split('=')
        lhs = sympify(lhs.strip(), locals=symbols_dict)
        rhs = sympify(rhs.strip(), locals=symbols_dict)
        equation = Eq(lhs, rhs)

        coeff_row = [float(lhs.coeff(var).evalf()) for var in symbol_list]
        coefficients.append(coeff_row)

        constant = (rhs - lhs.subs({var: 0 for var in symbol_list})).evalf()
        constants.append(float(constant))

    A = np.array(coefficients, dtype=float)
    B = np.array(constants, dtype=float).flatten()

    return A, B

In [22]:
equations = [
    "3*x + 3*y - 6*z = -18",
    "12*x - 3*y + 6*z = 48",
    "2*x + 2*y + 4*z = 36",
]

A, B = parse_equations(equations)

print("Matriks Koefisien (A):")
print(A)
print("\nMatriks Konstanta (B):")
print(B)

matriks = np.hstack((A, B.reshape(-1, 1)))
matriks = matriks.astype(np.float64)
print("\nMatriks Augmentasi:")
print(matriks)

Matriks Koefisien (A):
[[ 3.  3. -6.]
 [12. -3.  6.]
 [ 2.  2.  4.]]

Matriks Konstanta (B):
[-18.  48.  36.]

Matriks Augmentasi:
[[  3.   3.  -6. -18.]
 [ 12.  -3.   6.  48.]
 [  2.   2.   4.  36.]]


### Cara Manual

catatan: Satu utama berurutan secara diagonal dari kiri atas ke kanan bawah

In [23]:
def print_iterasi(i, matriks):
    print(f"Iterasi {i}:\n")
    print(matriks)
    print("\n")

In [24]:
i = 0
satu_utama_0 = False
satu_utama_1 = False
satu_utama_2 = False

if matriks[0,0] != 0:
    matriks[0,:] = np.round(matriks[0,:] * (1/matriks[0,0]), decimals=2)
    i += 1
    satu_utama_0 = True
    print_iterasi(i, matriks)

if matriks[1,0] != 0 and satu_utama_0:
    matriks[1,:] = np.round(matriks[0,:] * (-matriks[1,0]) + matriks[1,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[2,0] != 0 and satu_utama_0:
    matriks[2,:] = np.round(matriks[0,:] * (-matriks[2,0]) + matriks[2,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[1,1] != 0:
    matriks[1,:] = np.round(matriks[1,:] * (1/matriks[1,1]), decimals=2)
    i += 1
    satu_utama_1 = True
    print_iterasi(i, matriks)

if matriks[2,1] != 0 and satu_utama_1:
    matriks[2,:] = np.round(matriks[1,:] * (-matriks[2,1]) + matriks[2,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[2,2] != 0:
    matriks[2,:] = np.round(matriks[2,:] * (1/matriks[2,2]), decimals=2)
    i += 1
    satu_utama_2 = True
    print_iterasi(i, matriks)

if matriks[1,2] != 0 and satu_utama_2:
    matriks[1,:] = np.round(matriks[2,:] * (-matriks[1,2]) + matriks[1,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[0,2] != 0 and satu_utama_2:
    matriks[0,:] = np.round(matriks[2,:] * (-matriks[0,2]) + matriks[0,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[0,1] != 0 and satu_utama_1:
    matriks[0,:] = np.round(matriks[1,:] * (-matriks[0,1]) + matriks[0,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

Iterasi 1:

[[ 1.  1. -2. -6.]
 [12. -3.  6. 48.]
 [ 2.  2.  4. 36.]]


Iterasi 2:

[[  1.   1.  -2.  -6.]
 [  0. -15.  30. 120.]
 [  2.   2.   4.  36.]]


Iterasi 3:

[[  1.   1.  -2.  -6.]
 [  0. -15.  30. 120.]
 [  0.   0.   8.  48.]]


Iterasi 4:

[[ 1.  1. -2. -6.]
 [-0.  1. -2. -8.]
 [ 0.  0.  8. 48.]]


Iterasi 5:

[[ 1.  1. -2. -6.]
 [-0.  1. -2. -8.]
 [ 0.  0.  1.  6.]]


Iterasi 6:

[[ 1.  1. -2. -6.]
 [ 0.  1.  0.  4.]
 [ 0.  0.  1.  6.]]


Iterasi 7:

[[1. 1. 0. 6.]
 [0. 1. 0. 4.]
 [0. 0. 1. 6.]]


Iterasi 8:

[[1. 0. 0. 2.]
 [0. 1. 0. 4.]
 [0. 0. 1. 6.]]




### Cara otomatis

In [25]:
matriks_auto = np.linalg.solve(A, B)
matriks_auto

array([2., 4., 6.])

## Cari determinan dengan Segitiga Atas

In [34]:
equations = [
    "- 5*x + 7*z = -32",
    "3*y - 6*z = 48",
    "2*x + y + 4*z = -24",
]

A, B = parse_equations(equations)

print("Matriks Koefisien (A):")
print(A)
print("\nMatriks Konstanta (B):")
print(B)

Matriks Koefisien (A):
[[-5.  0.  7.]
 [ 0.  3. -6.]
 [ 2.  1.  4.]]

Matriks Konstanta (B):
[-32.  48. -24.]


In [35]:
Ax = A.copy()
Ay = A.copy()
Az = A.copy()
Ax[:,0] = B
Ay[:,1] = B
Az[:,2] = B

In [36]:
def segitiga_atas(matriks, determinan):
    matriks = matriks.astype(np.float64)
    n = matriks.shape[0]
    i = 0

    for col in range(n):
        if matriks[col, col] == 0:
            determinan = 0
            return matriks, determinan

        for row in range(col + 1, n):
            if matriks[row, col] != 0:
                factor = matriks[row, col] / matriks[col, col]
                matriks[row, :] -= factor * matriks[col, :]
                matriks[row, :] = np.round(matriks[row, :], decimals=2)
                i += 1
                print(f"Iterasi {i} (row {row} - factor {factor:.2f}):\n{matriks}\n")

    determinan = np.prod(np.diag(matriks))
    return matriks, determinan

### Determinan

In [37]:
A, determinan_A = segitiga_atas(A, -1)
print(f"\nDeterminan A: {determinan_A}")

Iterasi 1 (row 2 - factor -0.40):
[[-5.   0.   7. ]
 [ 0.   3.  -6. ]
 [ 0.   1.   6.8]]

Iterasi 2 (row 2 - factor 0.33):
[[-5.   0.   7. ]
 [ 0.   3.  -6. ]
 [ 0.   0.   8.8]]


Determinan A: -132.0


In [38]:
Ax, determinan_Ax = segitiga_atas(Ax, -1)
print(f"\nDeterminan Ax: {determinan_Ax}")

Iterasi 1 (row 1 - factor -1.50):
[[-32.    0.    7. ]
 [  0.    3.    4.5]
 [-24.    1.    4. ]]

Iterasi 2 (row 2 - factor 0.75):
[[-32.     0.     7.  ]
 [  0.     3.     4.5 ]
 [  0.     1.    -1.25]]

Iterasi 3 (row 2 - factor 0.33):
[[-32.     0.     7.  ]
 [  0.     3.     4.5 ]
 [  0.     0.    -2.75]]


Determinan Ax: 264.0


In [39]:
Ay, determinan_Ay = segitiga_atas(Ay, -1)
print(f"\nDeterminan Ay: {determinan_Ay}")

Iterasi 1 (row 2 - factor -0.40):
[[ -5.  -32.    7. ]
 [  0.   48.   -6. ]
 [  0.  -36.8   6.8]]

Iterasi 2 (row 2 - factor -0.77):
[[ -5.  -32.    7. ]
 [  0.   48.   -6. ]
 [  0.    0.    2.2]]


Determinan Ay: -528.0


In [40]:
Az, determinan_Az = segitiga_atas(Az, -1)
print(f"\nDeterminan Az: {determinan_Az}")

Iterasi 1 (row 2 - factor -0.40):
[[ -5.    0.  -32. ]
 [  0.    3.   48. ]
 [  0.    1.  -36.8]]

Iterasi 2 (row 2 - factor 0.33):
[[ -5.    0.  -32. ]
 [  0.    3.   48. ]
 [  0.    0.  -52.8]]


Determinan Az: 792.0


### Cara Otomatis

In [41]:
determinan_auto_A = np.linalg.det(A)
determinan_auto_Ax = np.linalg.det(Ax)
determinan_auto_Ay = np.linalg.det(Ay)
determinan_auto_Az = np.linalg.det(Az)

print(f"Determinan A: {determinan_auto_A}")
print(f"Determinan Ax: {determinan_auto_Ax}")
print(f"Determinan Ay: {determinan_auto_Ay}")
print(f"Determinan Az: {determinan_auto_Az}")

Determinan A: -131.99999999999997
Determinan Ax: 263.99999999999994
Determinan Ay: -528.0
Determinan Az: 792.0000000000001


### Nilai x,y,z

In [42]:
x = determinan_Ax / determinan_A
y = determinan_Ay / determinan_A
z = determinan_Az / determinan_A
print(f"Nilai x: {x}")
print(f"Nilai y: {y}")
print(f"Nilai z: {z}")

Nilai x: -2.0
Nilai y: 4.0
Nilai z: -6.0
