# Kuis 4

## Mencari basis dari vektor-vektor

In [118]:
import numpy as np

In [115]:
matriks = np.array([[6, -2, 7, 6], 
                   [4, -2, 4, -3], 
                   [-5, 6, -6, -5],
                   [5, -7, 4, -9],
                   [-4, 5, 7, -3]]).astype(np.float64)
matriks_asli = matriks.copy()
matriks = matriks.T
print(matriks)

[[ 6.  4. -5.  5. -4.]
 [-2. -2.  6. -7.  5.]
 [ 7.  4. -6.  4.  7.]
 [ 6. -3. -5. -9. -3.]]


In [110]:
def print_iterasi(i, matriks):
    print(f"Iterasi {i}:\n")
    print(matriks)
    print("\n")

In [111]:
i = 0
satu_utama_0 = False
satu_utama_1 = False
satu_utama_2 = False
satu_utama_3 = False

if matriks[0,0] != 0:
    matriks[0,:] = np.round(matriks[0,:] * (1/matriks[0,0]), decimals=2)
    i += 1
    satu_utama_0 = True
    print_iterasi(i, matriks)

if matriks[1,0] != 0 and satu_utama_0:
    matriks[1,:] = np.round(matriks[0,:] * (-matriks[1,0]) + matriks[1,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[2,0] != 0 and satu_utama_0:
    matriks[2,:] = np.round(matriks[0,:] * (-matriks[2,0]) + matriks[2,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[3,0] != 0 and satu_utama_0:
    matriks[3,:] = np.round(matriks[0,:] * (-matriks[3,0]) + matriks[3,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[1,1] != 0:
    matriks[1,:] = np.round(matriks[1,:] * (1/matriks[1,1]), decimals=2)
    i += 1
    satu_utama_1 = True
    print_iterasi(i, matriks)

if matriks[2,1] != 0 and satu_utama_1:
    matriks[2,:] = np.round(matriks[1,:] * (-matriks[2,1]) + matriks[2,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[3,1] != 0 and satu_utama_1:
    matriks[3,:] = np.round(matriks[1,:] * (-matriks[3,1]) + matriks[3,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[2,2] != 0:
    matriks[2,:] = np.round(matriks[2,:] * (1/matriks[2,2]), decimals=2)
    i += 1
    satu_utama_2 = True
    print_iterasi(i, matriks)
    
if matriks[3,2] != 0 and satu_utama_2:
    matriks[3,:] = np.round(matriks[2,:] * (-matriks[3,2]) + matriks[3,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[3,3] != 0:
    matriks[3,:] = np.round(matriks[3,:] * (1/matriks[3,3]), decimals=2)
    i += 1
    satu_utama_3 = True
    print_iterasi(i, matriks)

Iterasi 1:

[[ 1.    0.67 -0.83  0.83 -0.67]
 [-2.   -2.    6.   -7.    5.  ]
 [ 7.    4.   -6.    4.    7.  ]
 [ 6.   -3.   -5.   -9.   -3.  ]]


Iterasi 2:

[[ 1.    0.67 -0.83  0.83 -0.67]
 [ 0.   -0.66  4.34 -5.34  3.66]
 [ 7.    4.   -6.    4.    7.  ]
 [ 6.   -3.   -5.   -9.   -3.  ]]


Iterasi 3:

[[ 1.    0.67 -0.83  0.83 -0.67]
 [ 0.   -0.66  4.34 -5.34  3.66]
 [ 0.   -0.69 -0.19 -1.81 11.69]
 [ 6.   -3.   -5.   -9.   -3.  ]]


Iterasi 4:

[[  1.     0.67  -0.83   0.83  -0.67]
 [  0.    -0.66   4.34  -5.34   3.66]
 [  0.    -0.69  -0.19  -1.81  11.69]
 [  0.    -7.02  -0.02 -13.98   1.02]]


Iterasi 5:

[[  1.     0.67  -0.83   0.83  -0.67]
 [ -0.     1.    -6.58   8.09  -5.55]
 [  0.    -0.69  -0.19  -1.81  11.69]
 [  0.    -7.02  -0.02 -13.98   1.02]]


Iterasi 6:

[[  1.     0.67  -0.83   0.83  -0.67]
 [ -0.     1.    -6.58   8.09  -5.55]
 [  0.     0.    -4.73   3.77   7.86]
 [  0.    -7.02  -0.02 -13.98   1.02]]


Iterasi 7:

[[  1.     0.67  -0.83   0.83  -0.67]
 [ -0.  

In [117]:
if satu_utama_0:
    v1 = matriks_asli[0,:]
    print(f"v1 = {v1}\n")

if satu_utama_1:
    v2 = matriks_asli[1,:]
    print(f"v2 = {v2}\n")

if satu_utama_2:
    v3 = matriks_asli[2,:]
    print(f"v3 = {v3}\n")

if satu_utama_3:
    v4 = matriks_asli[3,:]
    print(f"v4 = {v4}\n")

v1 = [ 6. -2.  7.  6.]

v2 = [ 4. -2.  4. -3.]

v3 = [-5.  6. -6. -5.]

v4 = [ 5. -7.  4. -9.]



## Gram Schimt -> Basis Orthonormal

In [124]:
u1 = np.array([-4, 8, 2])
u2 = np.array([7, -3, 6])
u3 = np.array([6, -3, 7])

In [127]:
v1 = u1/np.linalg.norm(u1)
v1 = v1.round(2)

v2 = u2 - np.dot(u2, v1) * v1
v2 = v2/np.linalg.norm(v2)
v2 = v2.round(2)

v3 = u3 - np.dot(u3, v1) * v1 - np.dot(u3, v2) * v2
v3 = v3/np.linalg.norm(v3)
v3 = v3.round(2)

In [130]:
print(f"v1 = {v1}\n")
print(f"Norma v1 = {np.linalg.norm(v1)}\n")
print(f"v2 = {v2}\n")
print(f"Norma v2 = {np.linalg.norm(v2)}\n")
print(f"v3 = {v3}\n")
print(f"Norma v3 = {np.linalg.norm(v3)}\n")

v1 = [-0.44  0.87  0.22]

Norma v1 = 0.9994498486667552

v2 = [0.59 0.09 0.8 ]

Norma v2 = 0.9980981915623333

v3 = [-0.69 -0.45  0.57]

Norma v3 = 1.0017484714238398



## Mencari Eigen Value

In [96]:
A = np.array([[0, -1, -3], 
              [2, 3, 3], 
              [-2, 1, 1]]).astype(np.float64)
eigenvalues = np.linalg.eigvals(A)
print(eigenvalues.round(2))

[ 2. -2.  4.]


## Mencari Eigen Vector

### Cara Manual

catatan: Satu utama berurutan secara diagonal dari kiri atas ke kanan bawah

In [92]:
def eigen_vector(A, eigenvalue):
    for k, elemen in enumerate(eigenvalue):
        print("############################\n")
        print(f'Eigenvalue {k+1} = {elemen}\n')
        eigen_mask = np.eye(A.shape[0]) * elemen
        eigen_mask = eigen_mask.astype(np.float64)
        matriks = eigen_mask - A
        matriks = matriks.astype(np.float64)
        
        i = 0
        satu_utama_0 = False
        satu_utama_1 = False
        if matriks[0,0] != 0:
            matriks[0,:] = np.round(matriks[0,:] * (1/matriks[0,0]), decimals=2)
            i += 1
            satu_utama_0 = True
            print_iterasi(i, matriks)

        if matriks[1,0] != 0 and satu_utama_0:
            matriks[1,:] = np.round(matriks[0,:] * (-matriks[1,0]) + matriks[1,:], decimals=2)
            i += 1
            print_iterasi(i, matriks)

        if matriks[2,0] != 0 and satu_utama_0:
            matriks[2,:] = np.round(matriks[0,:] * (-matriks[2,0]) + matriks[2,:], decimals=2)
            i += 1
            print_iterasi(i, matriks)

        if matriks[1,1] != 0:
            matriks[1,:] = np.round(matriks[1,:] * (1/matriks[1,1]), decimals=2)
            i += 1
            satu_utama_1 = True
            print_iterasi(i, matriks)

        if matriks[2,1] != 0 and satu_utama_1:
            matriks[2,:] = np.round(matriks[1,:] * (-matriks[2,1]) + matriks[2,:], decimals=2)
            i += 1
            print_iterasi(i, matriks)

        if matriks[2,2] != 0:
            matriks[2,:] = np.round(matriks[2,:] * (1/matriks[2,2]), decimals=2)
            i += 1
            print_iterasi(i, matriks)

In [93]:
eigen_vector(A, eigenvalues.round(2))

############################

Eigenvalue 1 = 2.0

Iterasi 1:

[[ 1.   0.5  1.5]
 [-2.  -1.  -3. ]
 [ 2.  -1.   1. ]]


Iterasi 2:

[[ 1.   0.5  1.5]
 [ 0.   0.   0. ]
 [ 2.  -1.   1. ]]


Iterasi 3:

[[ 1.   0.5  1.5]
 [ 0.   0.   0. ]
 [ 0.  -2.  -2. ]]


Iterasi 4:

[[ 1.   0.5  1.5]
 [ 0.   0.   0. ]
 [-0.   1.   1. ]]


############################

Eigenvalue 2 = -2.0

Iterasi 1:

[[ 1.  -0.5 -1.5]
 [-2.  -5.  -3. ]
 [ 2.  -1.  -3. ]]


Iterasi 2:

[[ 1.  -0.5 -1.5]
 [ 0.  -6.  -6. ]
 [ 2.  -1.  -3. ]]


Iterasi 3:

[[ 1.  -0.5 -1.5]
 [ 0.  -6.  -6. ]
 [ 0.   0.   0. ]]


Iterasi 4:

[[ 1.  -0.5 -1.5]
 [-0.   1.   1. ]
 [ 0.   0.   0. ]]


############################

Eigenvalue 3 = 4.0

Iterasi 1:

[[ 1.    0.25  0.75]
 [-2.    1.   -3.  ]
 [ 2.   -1.    3.  ]]


Iterasi 2:

[[ 1.    0.25  0.75]
 [ 0.    1.5  -1.5 ]
 [ 2.   -1.    3.  ]]


Iterasi 3:

[[ 1.    0.25  0.75]
 [ 0.    1.5  -1.5 ]
 [ 0.   -1.5   1.5 ]]


Iterasi 4:

[[ 1.    0.25  0.75]
 [ 0.    1.   -1.  ]
 [ 0.   -